version: 0.2

phases:
  pre_build:
    commands:
      - echo Install aws cli
      - sudo apt-get install awscli -y
      - echo Loggin AWS ECR
      - $(aws ecr get-login --region ap-southeast-1 --no-include-email)

  build:
    commands:
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .

  post_build:
    commands:
      - docker push 131304515891.dkr.ecr.ap-southeast-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
