version: 0.2

phases:
  pre_build:
    commands:
      - echo Loggin AWS ECR
      - $(aws ecr get-login --region ap-southeast-1 --no-include-email)

  build:
    commands:
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .

  post_build:
    commands:
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG

artifacts:
  files:
    - 'scripts/*'
    - 'appspec.yml'
